[logger]
mode = "Trace"
logFileName = "./logs/auth.log"

[database]
dataSourceName = "./db/auth.db"

[server]
httpHostPort = 8033 
readTimeout = 5000000000 # in nanoseconds
writeTimeout = 10000000000 # in nanoseconds

[token]
expireInToken = 24 # in hours