[logger]
mode = "Trace"
logFileName = "auth.log"

[database]
dataSourceName = "auth.db"

[server]
httpHostPort = 8020 
readTimeout = 5000000000 # in nanoseconds
writeTimeout = 10000000000 # in nanoseconds

[token]
expireInToken = 24 # in hours