[logger]
mode = "Trace"
logFileName = "auth.log"

[database]
dataSourceName = "auth.db"

[server]
#httpHostIp = "10.194.7.224"  
httpHostPort = 8088 
readTimeout = 5000000000 # in nanoseconds
writeTimeout = 10000000000 # in nanoseconds
handlerTimeout = 12000000000 # in nanoseconds
hLTimeout = 10000000000 # in nanoseconds
deployTimeout = 7000000000 # in nanoseconds
transactionTimeout = 5000000000 # in nanoseconds     

[token]
expireInToken = 24 # in hours

